### ISSUE TITLE
Find a better name for the project

### ISSUE THREAD

**Issue by ischurov** [SaniyaZ/Thirtythreecows#1]
As I believe we will finally produce some world-usable library, so it is better to give some descriptive name to the project at the very beginning (actually, I don't like «Математики» even as internal name for the project).

And the name has to be fun. Boring project names should be banned by the Constitution. And all the other boring things too.

What about `thirtythreecows`?

**Comment by tpashaa** [comment]
Мне нравится!
Ну или уже использовавшиеся "полтора землекопа".

**Comment by ischurov** [comment]
@tpashaa , да, я об этом тоже думал, но не придумал, как это на английский кратко перевести :)

**Comment by SaniyaZ** [comment]
"Thirtythreecows" тоже интересно :) Но "полтора землекопа" эффектнее. Мне "Полтора землекопа" очень понравилось!  :) А обязательно на английский переводить?

**Comment by tpashaa** [comment]
"1,5 diggers»?
не, всё же коровки звучит лучше

**Comment by SaniyaZ** [comment]
"half diggers" ))

**Comment by SaniyaZ** [comment]
Ой "one and half diggers"

**Comment by SaniyaZ** [comment]
действительно длинное

**Comment by ischurov** [comment]
@SaniyaZ Да, на английский нужно переводить, это же будет и название библиотеки, оно должно быть на английском (ну, по крайней мере, латиницей, но транслит ужасен, если используется не по назначению). Вот примерно [так](https://github.com/SaniyaZ/Project-Mathematics/wiki) это будет выглядеть, обратите внимание на строчку с `import`.

Переименуете проект? (Это можно сделать в его настройках.)
